name: run booker api test

on: workflow_dispatch

jobs:
  run-api-test:
    runs-on: ubuntu-latest

    steps:
      - name: pull the project into the runner
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
                  distribution: 'temurin' # See 'Supported distributions' for available options
                  java-version: '11'

      - name: run api test using maven command
        run: mvn test